### ISSUE TITLE
cp: proxifier.template: No such file or directory

### ISSUE THREAD

**Issue by kas** [m4rkw/tethery#1]
I am getting error

`cp: proxifier.template: No such file or directory`

After executing `tethery.sh`. I am using the trial version of Proxifier v2.17. The Proxifier app opens fine after executing the script but [this guide](https://www.reddit.com/r/iphone/comments/55bbac/guide_how_to_tether_your_macbook_to_your_ios/) is not working so I believe my issue is that `proxifier.template` is not being copied correctly in the script.

Has anyone else had this issue? I am on OS X El Capitan 10.11.6.

 I will poke around in the `tethery.sh` file to see if I can fix my issue. I'll keep you posted. Please let me know if you need any more information regarding this issue.

**Comment by kas** [comment]
I fixed the issue by changing the path from `proxifier.template` to `~/Downloads/tethery-master/proxifier.template`

Seems like a quick fix

**Comment by m4rkw** [comment]
You should run the script from the directory it's in.  Sorry I didn't see this issue before, not sure why it didn't alert me.
